spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/kirangrandhi/fincity/saas/configfiles
server:
  port: 8888
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/