spring:
  application:
    name: gateway
  config:
   import: configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:8888}/
  profiles:
    active: ${SPRING_PROFILE:default} 
     
management:
  endpoint:
    gateway:
      enabled: true
      
server:
  port: 8080