security:
  db:
    url: r2dbc:mysql://localhost:3306/security
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/security
spring:
  flyway:
    enabled: false
