security:
  db:
    url: r2dbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/security

files:
  db:
    url: r2dbc:mysql://localhost:3306/files?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/files
  resources:
    location:
      static: C:/fincity/resources/static
      secured: C:/fincity/resources/secured

data:
  db:
    url: r2dbc:mysql://localhost:3306/data?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/data

ui:
  mongo:
    uri: mongodb://root:Kiran%40123@localhost:27017/ui?authSource=admin

core:
  mongo:
    uri: mongodb://root:Kiran%40123@localhost:27017/core?authSource=admin

spring:
  flyway:
    enabled: false
  cache:
    type: NONE

redis:
  url: redis://kiran%40123@localhost:6379
  codec: json
  cache:
    prefix: cmn

logging:
  level:
    root: INFO
    com.fincity: DEBUG
    org.jooq: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
