security:
  db:
    url: r2dbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: Surendhar@Mysql
    flyway:
      url: jdbc:mysql://localhost:3306/security

files:
  db:
    url: r2dbc:mysql://localhost:3306/files?serverTimezone=UTC
    username: root
    password: Surendhar@Mysql
    flyway:
      url: jdbc:mysql://localhost:3306/files
  resources:
    location:
      static: /Users/surendhar.s/files_test/static
      secured: /Users/surendhar.s/files_test/secured

ui:
  mongo:
    uri: mongodb://root:surendar123@localhost:27017/ui?authSource=admin

core:
  mongo:
    uri: mongodb://root:surendar123@localhost:27017/core?authSource=admin
  db:
    url: r2dbc:mysql://localhost:3306/core?serverTimezone=UTC
    username: root
    password: Surendhar@Mysql
    flyway:
      url: jdbc:mysql://localhost:3306/core

spring:
  flyway:
    enabled: false
  cache:
    type: NONE

redis:
  url: redis://surendhar.s@localhost:6379
  codec: object
  cache:
    prefix: cmn

logging:
  level:
    root: INFO
    com.fincity: DEBUG
    org.jooq: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    sun.rmi: INFO
    javax.management.remote.rmi: INFO
    org.springframework.beans.factory.support: INFO
    org.springframework.web.client.RestTemplate: INFO

mq:
  host: localhost
  port: 5672
  username: fincity
  password: fincity
