security:
  db:
    url: r2dbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/security

ui:
  mongo:
    uri: mongodb://root:Kiran%40123@localhost:27017/ui?authSource=admin

spring:
  flyway:
    enabled: false

logging:
  level:
    root: INFO
