security:
  db:
    url: r2dbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/security

ui:
  mongo:
    host: localhost
    port: 27017
    user: root
    password: Kiran@123
    authdatabase: admin

spring:
  flyway:
    enabled: false

logging:
  level:
    root: INFO
