security:
  db:
    url: r2dbc:mysql://localhost:3306/security?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/security
  subdomain:
    endings: fincity.ai,local.com

files:
  db:
    url: r2dbc:mysql://localhost:3306/files?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/files
  resources:
    location:
      static: /Users/kirangrandhi/Downloads/files/static
      secured: /Users/kirangrandhi/Downloads/files/secured

ui:
  mongo:
    uri: mongodb://root:Kiran%40123@localhost:27017/ui?authSource=admin

core:
  mongo:
    uri: mongodb://root:Kiran%40123@localhost:27017/core?authSource=admin
  db:
    url: r2dbc:mysql://localhost:3306/core?serverTimezone=UTC
    username: root
    password: Kiran@123
    flyway:
      url: jdbc:mysql://localhost:3306/core

spring:
  flyway:
    enabled: false

redis:
  url: redis://kiran%40123@localhost:6379
  codec: object
  cache:
    prefix: cmn

logging:
  level:
    root: INFO
    com.fincity: DEBUG
    org.jooq: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    sun.rmi: INFO
    javax.management.remote.rmi: INFO
    org.springframework.beans.factory.support: INFO
    org.springframework.web.client.RestTemplate: INFO

mq:
  host: localhost
  port: 5672
  username: fincity
  password: fincity
