spring:
  r2dbc:
    url: ${multi.db.url}
    username: ${multi.db.username}
    password: ${multi.db.password}
    pool:
      initial-size: 2
      max-size: 4
      max-idle-time: 30m
      validation-query: SELECT 1
  flyway:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${multi.db.flyway.url}
    user: ${multi.db.username}
    password: ${multi.db.password}
  boot:
    admin:
      client:
        instance:
          name: Multi
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  cloud:
    gateway:
      routes:
        - id: multi
          uri: lb://multi
          predicates:
            - Path=/api/multi/**, /*/api/multi/**, /*/*/api/multi/**, /*/*/*/api/multi/**, /*/*/*/*/api/multi/**, /*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/*/*/api/multi/**, /*/*/*/*/*/*/*/*/*/api/multi/**,

management:
  endpoint:
    flyway:
      enabled: true

redis:
  cache:
    prefix: mul
