spring:
  data:
    mongodb:
      uri: ${ui.mongo.uri}

  boot:
    admin:
      client:
        instance:
          name: UI
  cloud:
    gateway:
      routes:
        - id: ui
          uri: lb://ui
          predicates:
            - Path=/api/ui/**, /*/api/ui/**, /*/*/api/ui/**, /*/*/*/api/ui/**, /*/*/*/*/api/ui/**
