spring:
  data:
    mongodb:
      host: ${ui.mongo.host}
      port: ${ui.mongo.port}
      database: ${ui.mongo.database:ui}
      authenticationDatabase: ${ui.mongo.authdatabase:admin}
      password: ${ui.mongo.password}
      username: ${ui.mongo.user:root}
  boot:
    admin:
      client:
        instance:
          name: UI
  cloud:
    gateway:
      routes:
        - id: ui
          uri: lb://ui
          predicates:
            - Path=/api/ui/**, /*/api/ui/**, /*/*/api/ui/**, /*/*/*/api/ui/**, /*/*/*/*/api/ui/**
