spring:
  data:
    mongodb:
      host: ${ui.mongo.host}
      port: ${ui.mongo.port}
      database: ${ui.mongo.authdb:ui}
      authenticationDatabase: ${ui.mongo.authdb:admin}
      password: ${ui.mongo.password}
      user: ${ui.mongo.user:root}
  boot:
    admin:
      client:
        instance:
          name: UI
