name: Setup Binary Artifacts

on:
  #To trigger manually
  workflow_dispatch:
  push:
    branches: [development]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: development
      - name: Setting up Java
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "adopt"
      - name: Building commons
        working-directory: ./commons
        run: mvn clean install
      - name: Building commons-jooq
        working-directory: ./commons-jooq
        run: mvn clean install
      - name: Building commons-security
        working-directory: ./commons-security
        run: mvn clean install
      - name: Building commons-mongo
        working-directory: ./commons-mongo
        run: mvn clean install
      - name: Building admin
        working-directory: ./admin
        run: mvn clean install
      - name: Building config
        working-directory: ./config
        run: mvn clean install
      - name: Building eureka
        working-directory: ./eureka
        run: mvn clean install
      - name: Building gateway
        working-directory: ./gateway
        run: mvn clean install
      - name: Building security
        working-directory: ./security
        run: mvn clean install
      - name: Building ui
        working-directory: ./ui
        run: mvn clean install
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
