name: Dev Deployment

on:
  #To trigger manually
  workflow_dispatch:
  push:
    branches: [development]

env:
  ENVIRONMENT: development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: development
      - name: Setting up Java
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "adopt"
      - name: Building commons
        working-directory: ./commons
        run: mvn clean install
      - name: Building commons-jooq
        working-directory: ./commons-jooq
        run: mvn clean install
      - name: Building commons-security
        working-directory: ./commons-security
        run: mvn clean install
      - name: Building commons-mongo
        working-directory: ./commons-mongo
        run: mvn clean install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Building admin
        working-directory: ./admin
        run: |
          mvn install
          aws s3 sync ./target/*.jar s3://nclc-deployment/development
      - name: Building config
        working-directory: ./config
        run: |
          mvn install
          aws s3 sync ./target/*.jar s3://nclc-deployment/development
      - name: Building eureka
        working-directory: ./eureka
        run: mvn clean install
      - name: Deploy
        run: aws s3 sync ./eureka/target/*.jar s3://nclc-deployment/development
      - name: Building gateway
        working-directory: ./gateway
        run: mvn clean install
      - name: Deploy
        run: aws s3 sync ./gateway/target/*.jar s3://nclc-deployment/development
      - name: Building security
        working-directory: ./security
        run: mvn clean install
      - name: Deploy
        run: aws s3 sync ./security/target/*.jar s3://nclc-deployment/development
      - name: Building ui
        working-directory: ./ui
        run: mvn clean install
      - name: Deploy
        run: aws s3 sync ./ui/target/*.jar s3://nclc-deployment/development
